<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mis="http://zakupki.gov.ru/fz44/get-docs-mis/ws" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://zakupki.gov.ru/oos/base/1" targetNamespace="http://zakupki.gov.ru/fz44/get-docs-mis/ws">
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://zakupki.gov.ru/fz44/get-docs-mis/ws" schemaLocation="../getDocsMIS-ws-api.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="getPublicDocsRequest">
		<wsdl:part name="getPublicDocsMisRequest" element="mis:getPublicDocsRequest"/>
	</wsdl:message>
	<wsdl:message name="getPublicDocsResponse">
		<wsdl:part name="getPublicDocsResponse" element="mis:getPublicDocsResponse"/>
	</wsdl:message>
	<wsdl:message name="getHiddenDocsRequest">
		<wsdl:part name="getHiddenDocsResponse" element="mis:getHiddenDocsRequest"/>
	</wsdl:message>
	<wsdl:message name="getHiddenDocsResponse">
		<wsdl:part name="getHiddenDocsResponse" element="mis:getHiddenDocsResponse"/>
	</wsdl:message>
	<wsdl:message name="getPublicDocsByReestrNumberRequest">
		<wsdl:part name="getPublicDocsByReestrNumberRequest" element="mis:getPublicDocsByReestrNumberRequest"/>
	</wsdl:message>
	<wsdl:message name="getPublicDocsByReestrNumberResponse">
		<wsdl:part name="getPublicDocsByReestrNumberResponse" element="mis:getPublicDocsByReestrNumberResponse"/>
	</wsdl:message>
	<wsdl:message name="getHiddenDocsByReestrNumberRequest">
		<wsdl:part name="getHiddenDocsByReestrNumberRequest" element="mis:getHiddenDocsByReestrNumberRequest"/>
	</wsdl:message>
	<wsdl:message name="getHiddenDocsByReestrNumberResponse">
		<wsdl:part name="getHiddenDocsByReestrNumberResponse" element="mis:getHiddenDocsByReestrNumberResponse"/>
	</wsdl:message>
	<wsdl:message name="getPublicDocsByOrgRegionRequest">
		<wsdl:part name="getPublicDocsByOrgRegionRequest" element="mis:getPublicDocsByOrgRegionRequest"/>
	</wsdl:message>
	<wsdl:message name="getPublicDocsByOrgRegionResponse">
		<wsdl:part name="getPublicDocsByOrgRegionResponse" element="mis:getPublicDocsByOrgRegionResponse"/>
	</wsdl:message>
	<wsdl:message name="getHiddenDocsByOrgRegionRequest">
		<wsdl:part name="getHiddenDocsByOrgRegionRequest" element="mis:getHiddenDocsByOrgRegionRequest"/>
	</wsdl:message>
	<wsdl:message name="getHiddenDocsByOrgRegionResponse">
		<wsdl:part name="getHiddenDocsByOrgRegionResponse" element="mis:getHiddenDocsByOrgRegionResponse"/>
	</wsdl:message>
	<wsdl:message name="getDocSignaturesByUrlRequest">
		<wsdl:part name="getDocSignaturesByUrlRequest" element="mis:getDocSignaturesByUrlRequest"/>
	</wsdl:message>
	<wsdl:message name="getDocSignaturesByUrlResponse">
		<wsdl:part name="getDocSignaturesByUrlResponse" element="mis:getDocSignaturesByUrlResponse"/>
	</wsdl:message>
	<wsdl:message name="getHiddenBankDocsRequest">
		<wsdl:part name="getHiddenBankDocsRequest" element="mis:getHiddenBankDocsRequest"/>
	</wsdl:message>
	<wsdl:message name="getHiddenBankDocsResponse">
		<wsdl:part name="getHiddenBankDocsResponse" element="mis:getHiddenBankDocsResponse"/>
	</wsdl:message>
	<wsdl:message name="getPreparedPartRequest">
		<wsdl:part name="getPreparedPartRequest" element="mis:getPreparedPartRequest"/>
	</wsdl:message>
	<wsdl:message name="getPreparedPartResponse">
		<wsdl:part name="getPreparedPartResponse" element="mis:getPreparedPartResponse"/>
	</wsdl:message>
	<wsdl:message name="getAnalyticalReportsRequest">
		<wsdl:part name="getAnalyticalReportsRequest" element="mis:getAnalyticalReportsRequest"/>
	</wsdl:message>
	<wsdl:message name="getAnalyticalReportsResponse">
		<wsdl:part name="getAnalyticalReportsResponse" element="mis:getAnalyticalReportsResponse"/>
	</wsdl:message>
	<wsdl:message name="getNsiRequest">
		<wsdl:part name="getNsiRequest" element="mis:getNsiRequest"/>
	</wsdl:message>
	<wsdl:message name="getNsiResponse">
		<wsdl:part name="getNsiResponse" element="mis:getNsiResponse"/>
	</wsdl:message>
	<wsdl:message name="getPreparedArchivesRequest">
		<wsdl:part name="getPreparedArchivesRequest" element="mis:getPreparedArchivesRequest"/>
	</wsdl:message>
	<wsdl:message name="getPreparedArchivesResponse">
		<wsdl:part name="getPreparedArchivesResponse" element="mis:getPreparedArchivesResponse"/>
	</wsdl:message>
	<wsdl:message name="getDocsParticularRequest">
		<wsdl:part name="getDocsParticularRequest" element="mis:getDocsParticularRequest"/>
	</wsdl:message>
	<wsdl:message name="getDocsParticularResponse">
		<wsdl:part name="getDocsParticularResponse" element="mis:getDocsParticularResponse"/>
	</wsdl:message>
	<wsdl:portType name="GetDocsMisFacade">
		<wsdl:operation name="getPublicDocs">
			<wsdl:input name="getPublicDocsRequest" message="mis:getPublicDocsRequest"/>
			<wsdl:output name="getPublicDocsResponse" message="mis:getPublicDocsResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getHiddenDocs">
			<wsdl:input name="getHiddenDocsRequest" message="mis:getHiddenDocsRequest"/>
			<wsdl:output name="getHiddenDocsResponse" message="mis:getHiddenDocsResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getPublicDocsByReestrNumber">
			<wsdl:input name="getPublicDocsByReestrNumberRequest" message="mis:getPublicDocsByReestrNumberRequest"/>
			<wsdl:output name="getPublicDocsByReestrNumberResponse" message="mis:getPublicDocsByReestrNumberResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getHiddenDocsByReestrNumber">
			<wsdl:input name="getHiddenDocsByReestrNumberRequest" message="mis:getHiddenDocsByReestrNumberRequest"/>
			<wsdl:output name="getHiddenDocsByReestrNumberResponse" message="mis:getHiddenDocsByReestrNumberResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getPublicDocsByOrgRegion">
			<wsdl:input name="getPublicDocsByOrgRegionRequest" message="mis:getPublicDocsByOrgRegionRequest"/>
			<wsdl:output name="getPublicDocsByOrgRegionResponse" message="mis:getPublicDocsByOrgRegionResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getHiddenDocsByOrgRegion">
			<wsdl:input name="getHiddenDocsByOrgRegionRequest" message="mis:getHiddenDocsByOrgRegionRequest"/>
			<wsdl:output name="getHiddenDocsByOrgRegionResponse" message="mis:getHiddenDocsByOrgRegionResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getDocSignaturesByUrl">
			<wsdl:input name="getDocSignaturesByUrlRequest" message="mis:getDocSignaturesByUrlRequest"/>
			<wsdl:output name="getDocSignaturesByUrlResponse" message="mis:getDocSignaturesByUrlResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getHiddenBankDocs">
			<wsdl:input name="getHiddenBankDocsRequest" message="mis:getHiddenBankDocsRequest"/>
			<wsdl:output name="getHiddenBankDocsResponse" message="mis:getHiddenBankDocsResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getPreparedPart">
			<wsdl:input name="getPreparedPartRequest" message="mis:getPreparedPartRequest"/>
			<wsdl:output name="getPreparedPartResponse" message="mis:getPreparedPartResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getAnalyticalReports">
			<wsdl:input name="getAnalyticalReportsRequest" message="mis:getAnalyticalReportsRequest"/>
			<wsdl:output name="getAnalyticalReportsResponse" message="mis:getAnalyticalReportsResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getNsi">
			<wsdl:input name="getNsiRequest" message="mis:getNsiRequest"/>
			<wsdl:output name="getNsiResponse" message="mis:getNsiResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getPreparedArchives">
			<wsdl:input name="getPreparedArchivesRequest" message="mis:getPreparedArchivesRequest"/>
			<wsdl:output name="getPreparedArchivesResponse" message="mis:getPreparedArchivesResponse"/>
		</wsdl:operation>
		<wsdl:operation name="getDocsParticular">
			<wsdl:input name="getDocsParticularRequest" message="mis:getDocsParticularRequest"/>
			<wsdl:output name="getDocsParticularResponse" message="mis:getDocsParticularResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="GetDocsMisFacadeBinding" type="mis:GetDocsMisFacade">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getPublicDocs">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getPublicDocsRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getPublicDocsResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getHiddenDocs">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getHiddenDocsRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getHiddenDocsResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getPublicDocsByReestrNumber">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getPublicDocsByReestrNumberRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getPublicDocsByReestrNumberResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getHiddenDocsByReestrNumber">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getHiddenDocsByReestrNumberRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getHiddenDocsByReestrNumberResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getPublicDocsByOrgRegion">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getPublicDocsByOrgRegionRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getPublicDocsByOrgRegionResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getHiddenDocsByOrgRegion">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getHiddenDocsByOrgRegionRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getHiddenDocsByOrgRegionResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getDocSignaturesByUrl">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getDocSignaturesByUrlRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getDocSignaturesByUrlResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getHiddenBankDocs">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getHiddenBankDocsRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getHiddenBankDocsResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getPreparedPart">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getPreparedPartRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getPreparedPartResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getAnalyticalReports">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getAnalyticalReportsRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getAnalyticalReportsResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getNsi">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getNsiRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getNsiResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getPreparedArchives">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getPreparedArchivesRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getPreparedArchivesResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="getDocsParticular">
			<soap:operation soapAction="http://zakupki.gov.ru/fz44/ws/get-docs-mis"/>
			<wsdl:input name="getDocsParticularRequest">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getDocsParticularResponse">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="GetDocsMisFacadeService">
		<wsdl:port name="GetDocsMisFacadePort" binding="mis:GetDocsMisFacadeBinding">
			<soap:address location="https://int44.zakupki.gov.ru/eis-integration/services-mis/getDocsMis"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
